 heroku link-https://ssh-api-singh.herokuapp.com/

 for deployment heroku link-https://ssh-api-singh.herokuapp.com/v1/products


###              ******** DEPLYMENT TEST ***********
GET https://ssh-api-singh.herokuapp.com/v1/products

###
POST https://ssh-api-singh.herokuapp.com/v1/products/create

name=key
&quantity=50

###
DELETE https://ssh-api-singh.herokuapp.com/v1/products/622ef6515395bed026eded28

### update
POST  https://ssh-api-singh.herokuapp.com/v1/products/622ef6515395bed026eded28/update_quantity/?quantity=100 
